[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "ntex-grpc-derive",
  "prost-build",
  "examples/custom",
  "examples/helloworld"
]

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }
ntex-grpc-codegen = { path = "./ntex-grpc-codegen" }
ntex-grpc-derive = { path = "./ntex-grpc-derive" }
ntex-prost-build = { path = "./prost-build" }

ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-connect = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-io = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-service = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-util = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-tls = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-tokio = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-h2 = { git = "https://github.com/ntex-rs/ntex-h2.git", branch = "service-0-4" }
