[workspace]
members = [
  "ntex-grpc",
  "ntex-grpc-codegen",
  "ntex-grpc-derive",
  "prost-build",
  "examples/custom",
  "examples/helloworld"
]
resolver = "3"

[patch.crates-io]
ntex-grpc = { path = "./ntex-grpc" }